const DATABASE_NAME=process.env.DATABASE_NAME
const DATABASE_TYPE=process.env.DATABASE_TYPE
const DATABASE_USER=process.env.DATABASE_USER
const DATABASE_PASSWORD=process.env.DATABASE_PASSWORD
const DATABASE_PORT=process.env.DATABASE_PORT
const SERVER_PORT=process.env.SERVER_PORT
const NODE_ENV=process.env.NODE_ENV

export {DATABASE_NAME, DATABASE_PASSWORD, DATABASE_PORT, DATABASE_TYPE, DATABASE_USER, NODE_ENV, SERVER_PORT}